### ISSUE TITLE
[FEATURE] Creation and destruction API of App and Bus

### ISSUE THREAD

**Issue by BECATRUE** [snu-quiqcl/swift#66]
### Feature you want to implement
Our goal is the below:
- To orgranize `Swift` to be easily recognizable at a glance.
- To create or destroy a `Bus` and an `App` at any time.

### How the feature is implemented
`Swift` was implemented in `swift.swift` module.

#### Original structure
```python
class Swift(...):
  def __init__(...):
    self._init_bus(...)    # initialize global buses
    self._init_app(...)    # initialize apps
    self._show_frame(...)  # show frames of apps
```

#### Expected structure
```python
class Swift(...):
  def __init__(...):
    self.load(...)  # initialize buses and apps, and show frames

  def createBus(...):
    pass

  def createApp(...):
    pass

  def destroyBus(...):
    pass

  def destroyApp(...):
    pass
```

#### Documentations
`load(appInfos: dict, busInfos: dict)`
- Initialize the `Swift` and load the apps and buses based on the given information.
- Initailize `Bus`es and `App`s.
- Show `frame`s of `App`s.
- Use the new creation and destruction API.

`createBus(name: str)`
- Create a `Bus`.

`createApp(name: str, pos: str, show: bool, ...)`
- Create an `App` and show its `frame`s.

`destroyBus(name: str)`
- Destroy the `Bus`.

`destroyApp(name: str)`
- Destroy the `App`.
- Be aware that we should remove it from both `python` and `Qt`.

**Comment by kangz12345** [comment]
I edited it, so please ask me if there is something you don't understand.

**Comment by kangz12345** [comment]
Great, you may start!

**Comment by BECATRUE** [comment]
Oh, I have a question!

I think the argument `busNames` in `load` should be changed to a dict `busInfos`, since it may have a param, i.e. `timeout`.
How do you think about it?

@kangz12345

**Comment by kangz12345** [comment]
Right, I agree with you!

**Comment by kangz12345** [comment]
I would like to make `createBus()` and `createApp()` more stateless, i.e., they just create a bus or an app based on the given arguments (`name`, `path`, `module`, `show`, `pos`, etc.).

I don't think `setup_env` should be saved, because it is a _setup_ environment information, which is only necessary for setup.
Only the _current status_, which includes the list (or dict, etc.) of apps and buses, should be tracked, I think.

Therefore, what I want for this new API is supporting a way of addition or removal of apps and buses in `swift`. Of course, this shouldn't allowed to apps directly (they might use it in a bad manner). However, for this issue, it only provides the API via methods `Swift`, and the apps do not have the `Swift` instance, hence cannot call the API.

Later, we would make a special messaging API for the apps (let's talk about the details later..), so the apps can request `swift` to create or to destroy an app or a bus. The authorization would then happen, for example, `swift` pops up a dialog for the confirmation from the user.

**Comment by BECATRUE** [comment]
> I would like to make `createBus()` and `createApp()` more stateless, i.e., they just create a bus or an app based on the given arguments (`name`, `path`, `module`, `show`, `pos`, etc.).
> 
> I don't think `setup_env` should be saved, because it is a _setup_ environment information, which is only necessary for setup. Only the _current status_, which includes the list (or dict, etc.) of apps and buses, should be tracked, I think.
> 
> Therefore, what I want for this new API is supporting a way of addition or removal of apps and buses in `swift`. Of course, this shouldn't allowed to apps directly (they might use it in a bad manner). However, for this issue, it only provides the API via methods `Swift`, and the apps do not have the `Swift` instance, hence cannot call the API.
> 
> Later, we would make a special messaging API for the apps (let's talk about the details later..), so the apps can request `swift` to create or to destroy an app or a bus. The authorization would then happen, for example, `swift` pops up a dialog for the confirmation from the user.

Oh, I see.
I misunderstood that you intended offering only `show` and `pos` to `createApp`.

Then, I won't save `setup_env`.

**Comment by BECATRUE** [comment]
I have a problem..

In `createApp`, there are many arguments (e.g. `path`, `module`). Thus, it causes Pylint warning.

```console
swift\swift.py:100:4: R0913: Too many arguments (9/5) (too-many-arguments)
swift\swift.py:100:4: R0914: Too many local variables (16/15) (too-many-locals)
```

Thus, how about changing the arguments into a dict?

@kangz12345

**Comment by kangz12345** [comment]
I didn't know such lint rules 🤣
In that case, let's use [`namedtuple`](https://docs.python.org/3/library/collections.html#collections.namedtuple) or [`dataclasses`](https://docs.python.org/3/library/dataclasses.html) or anything else you think good enough, since we want to force the info structure.

For example, define `AppInfo` and `BusInfo` in `swift.swift` module as a namedtuple or a dataclass:
```python
info = AppInfo.from_dict(info_dict) # just an example; not necessarily this way
self.createApp(info)
```

In addition, I think `dataclasses` would be better since it is easier to define helpful methods inside.
Please let me know if you have opinions about this.

You can make another PR for this if you want.
How do you think?

**Comment by BECATRUE** [comment]
Originally, I tried to use a dict!
How about making another issue about `dataclasses`?

Before `dataclasses`, I want to request PR.

**Comment by kangz12345** [comment]
Oh, very good idea. Please make a PR now, and let's make the `dataclasses` in the next PR.

If you want to make it, you can do it.
If you want to develop the next step (regarding to #62), I will do this (dataclass).

**Comment by BECATRUE** [comment]
> Oh, very good idea. Please make a PR now, and let's make the `dataclasses` in the next PR.
> 
> If you want to make it, you can do it.
> If you want to develop the next step (regarding to #62), I will do this (dataclass).

Cool! Please make `dataclasses` after this issue.
